#include "context_change.hpp"
#include <iostream>

std::ostream &operator<<(std::ostream &os, const ContextChange cc) noexcept {

  static constexpr const char *const strs[] = {
      "STOP",
      "EL",
      "ER",
      "SL_REDIST",
      "IL",
      "GROW_SMALL",
      "GROW_LARGE",
      "SHRINK",
      "SORT",
      "CHANGE_STATUS",
      "GSO_PP",
      "LOAD_GSO",
      "HISTO",
      "BGJ1",
      "ORDERED_DB_SPLIT",
      "BUCKET",
      "DB_SIZE",
      "RESET_STATS",
      "DB_SPLIT_UIDS",
      "INSERT",
      "ADHOC_INSERT",
      "STOP_SIEVING",
      "STATS_LONG",
      "STATS_DOUBLE",
      "DUP_INSERT",
      "BUCKET_SIZES",
      "BUCKET_START",
      "REDIST_DB",
      "RESERVE",
      "GET_CPU_TIME",
      "GET_EXTRA_MEMORY",
      "RECONCILE_DB",
      "GET_GLOBAL_SATURATION",
      "CHANGE_ROOT_RANK",
      "COLLECT_MEMORY",
      "GATHER_BUCKETS",
      "SEND_TOPOLOGY",
      "BROADCAST_PARAMS",
      "BEST_LIFTS",
      "GET_DB",
      "SPLIT_DB",
      "GET_GLOBAL_VARIANCE",
      "GET_MIN_MAX_LEN",
      "LIFT_BOUNDS",
      "BGJ1_BUCKET_SEND",
      "BGJ1_CENTER_SEND",
      "BGJ1_SEND_SIZE",
      "BGJ1_PROCESS_STOP",
      "MESSAGES_FOR",
      "BANDWIDTH_FOR",
      "TOTAL_MESSAGES",
      "TOTAL_BANDWIDTH",
      "IS_ONE_G6K",
      "SL_NO_REDIST",
      "CHECK_FINAL_INSERTIONS",
      "GET_ADJUST_TIMINGS",
      "GET_UNIQUE_RATIO",
      "RESET_BANDWIDTH",
  };
  os << strs[static_cast<unsigned>(cc)];
  return os;
}
